DoggedFilly0/routes-configuration
KaliumStudios/plastech-inv pull request #2
Opened 2022-10-04 16:17 UTC by Alexlr20

Added routes fot the page

2022-10-04 20:27 UTC, TGMM requested changes

2022-10-04 20:27 UTC, TGMM commented on src/components/Navbar.tsx
> +  };
ElNav? ElUser?

2022-10-04 20:27 UTC, TGMM commented on package.json
> +    "@emotion/styled": "^11.10.4",
Estos no los usaste en ningún lado, ¿para qué son?

2022-10-04 20:27 UTC, TGMM commented on package.json
> +    "styled-components": "^5.3.6",
Same as above

2022-10-04 20:27 UTC, TGMM commented on src/components/Navbar.tsx
> +            }}
No me super encanta el inline css aunque sea un js object. Deberíamos tener un file como Navbar.style.ts en donde guardamos los objects como consts y en el tsx ya solo lo referencías. Con esto podrías reutilizar mejor los estilos (importar un .style a otro .style sin traerte todo el tsx) y es más fácil visualizar la separación de html y css.

2022-10-04 20:27 UTC, TGMM commented on src/components/Navbar.tsx
> +  };
No entiendo cómo estás haciendo el redirect. ¿No deberíamos de usar el [hook de useNavigate](https://stackoverflow.com/a/40380010/11257758)?

2022-10-04 20:27 UTC, TGMM commented on src/components/Production.tsx
> +}));
Esto si es muy nitpicky y lo puedes dejar así si quieres, pero creo que Item no es muy específico, no sé qué es si no veo el contexto.

2022-10-04 20:27 UTC, TGMM commented on src/components/Navbar.tsx
> +                <Avatar alt="Yep Cock" src="" sx={{ mr: 2.5 }} />
Supongo que el alt text se te olvidó cambiarlo.

2022-10-04 20:27 UTC, TGMM commented on src/components/Navbar.tsx
> +                  El Eliud de Leon{" "}
¿No funcionaría esto? `{" El Eliud de Leon "}`

2022-10-04 20:27 UTC, TGMM commented on src/components/Navbar.tsx
> +              open={Boolean(anchorElNav)}
También puedes hacer `!!anchorElNav`, ahí te dejo decidir.

2022-10-04 20:27 UTC, TGMM commented on src/App.css
>      transform: rotate(0deg);
Hay que decidir si nos vamos a quedar con archivos css o si vamos a hacer todo css-in-js. Pero no hay que mezclar los dos.

2022-10-04 20:27 UTC, TGMM commented on src/App.tsx
> +      <div className=" container">
Aquí cambiariamos el className por el objeto de js.

2022-10-04 20:27 UTC, TGMM commented on src/App.tsx
> +        </Routes>
Otro nitpick, pero hay que hacer que esto utilize el 100% de la pantalla restante, puedes no hacerlo ahorita pero en el futuro hay que verificar que quede.

2022-10-09 18:31 UTC, Alexlr20 commented on package.json
> +    "@emotion/styled": "^11.10.4",
No se utilizan pero se van a usar en el futuro

2022-10-09 18:35 UTC, Alexlr20 commented on src/components/Navbar.tsx
> +  };
Se utilizan con las Routes en el archivo de App.tsx

2022-10-09 18:36 UTC, Alexlr20 commented on src/components/Navbar.tsx
> +                <Avatar alt="Yep Cock" src="" sx={{ mr: 2.5 }} />
Yep

2022-10-09 18:36 UTC, Alexlr20 commented on src/components/Navbar.tsx
> +                  El Eliud de Leon{" "}
Fixed

2022-10-09 19:38 UTC, TGMM commented on src/components/Navbar.tsx
> +  };
Cambialo a que use el hook, porque si no no se comporta como una SPA

2022-10-09 19:40 UTC, TGMM commented on src/components/Navbar.tsx
> +                <Avatar alt="Yep Cock" src="" sx={{ mr: 2.5 }} />
Pero ps cambialo, no? xd

2022-10-09 19:40 UTC, TGMM commented on src/components/Navbar.tsx
> +                  El Eliud de Leon{" "}
Creo que te falta pushear tus commits

2022-10-10 05:17 UTC, TGMM requested changes

2022-10-10 05:17 UTC, TGMM commented on src/components/Navbar.tsx
> +  );
Me siguen sin gustar los nombres de "ElUser". No sé ni qué significa eso. Pero si lo quieres dejar así, 'ta bien.

2022-10-10 05:17 UTC, TGMM commented on src/components/Navbar.tsx
> +          <Box sx={{ flexGrow: 1, display: { xs: "flex", md: "none" } }}>
Si puedes, lo de los estilos hazlo en este mismo PR. Para establecer el precedente de como deben ir. También hay que mover los tests a un folder de tests, pero eso lo hacemos en otro PR.

2022-10-10 05:17 UTC, TGMM commented on src/components/Navbar.tsx
> +                  {" El ELiud de Leon "}
Si puedes, agregale un comment de TODO para saber que hay que cambiar este pedazo cuando tengamos la conexion a la base de datos.

2022-10-10 05:17 UTC, TGMM commented on src/styles/Common.styles.ts
> +export const App_link = {
No me gusta el nombre de esta variable. Cambialo a appLink o algo que esté en camelCase.

2022-10-10 16:26 UTC, DoggedFilly0 commented on src/components/Navbar.tsx
> +  );
Los prefiero dejar así para que no tengas tantos cambios al original

2022-10-10 19:42 UTC, TGMM commented on src/components/Navbar.tsx
> +  );
:/

2022-10-10 19:44 UTC, TGMM approved these changes

2022-10-10 19:44 UTC, merged